from common import *

def run():
    e=events().set_index(ID);raw=next(x for x in read(W/'inventory/large_input_identity.json') if x['key']=='raw');assert sha(raw['path'])==raw['sha256'];s=pd.read_csv(raw['path'],dtype=str,keep_default_na=False);s['source_row_number']=np.arange(1,len(s)+1);s[ID]=s[ID].str.strip();s['stage_num']=pd.to_numeric(s['Restoration Stage'],errors='coerce');s['customers']=pd.to_numeric(s['Number of Customers Restored'].str.replace(',',''),errors='coerce');s['start_utc']=pd.to_datetime(s['Start Date and Time'],format='mixed',utc=True,errors='coerce');s['source_key']=raw['sha256']+':'+s.source_row_number.astype(str)
    g=s.groupby(ID,sort=True);minnum=g.stage_num.transform('min');mintime=g.start_utc.transform('min');nt=s[s.stage_num.eq(minnum)];tt=s[s.start_utc.eq(mintime)];nsel=nt.sort_values([ID,'source_row_number'],kind='stable').drop_duplicates(ID).set_index(ID);tsel=tt.sort_values([ID,'source_row_number'],kind='stable').drop_duplicates(ID).set_index(ID)
    z=pd.DataFrame(index=e.index);z['aggregate_C']=e[C];z['minimum_stage_number']=g.stage_num.min();z['min_stage_tie_n']=nt.groupby(ID).size();z['min_stage_customer_unique_n']=nt.groupby(ID).customers.nunique(dropna=False);z['earliest_time_tie_n']=tt.groupby(ID).size();z['earliest_time_customer_unique_n']=tt.groupby(ID).customers.nunique(dropna=False)
    for prefix,chosen in [('min_stage',nsel),('earliest_time',tsel)]:
        for c in ['source_row_number','source_key','stage_num','start_utc','customers']:z[prefix+'_'+c]=chosen[c]
    z['R02_earliest_customer']=pd.to_numeric(e['Number of Customers Restored'],errors='coerce');z['R02_source_row']=e.selected_source_row;z['in_main']=e.candidate_main_E0;z['in_weather']=e.candidate_weather_E0;z['source_rows']=e.source_rows
    z['earliest_matches_R02_customer']=z.earliest_time_customers.eq(z.R02_earliest_customer)|(z.earliest_time_customers.isna()&z.R02_earliest_customer.isna());assert z.earliest_matches_R02_customer.all();assert z.earliest_time_source_row_number.eq(z.R02_source_row).all()
    rows=[];qa=[]
    for name,d in [('event_master',z),('main',z[z.in_main]),('weather',z[z.in_weather])]:
        cols=['aggregate_C','min_stage_customers','earliest_time_customers'];finite=np.isfinite(d[cols].astype(float));common=finite.all(axis=1);means=d.loc[common,cols].mean();own=d[cols].mean()
        for col in cols:rows.append({'population':name,'measure':col,'population_n':len(d),'own_valid_n':int(finite[col].sum()),'own_missing_n':int((~finite[col]).sum()),'own_mean':own[col],'common_valid_n':int(common.sum()),'common_mean':means[col],'ratio_aggregate_mean_to_measure_mean_common':means.aggregate_C/means[col],'ratio_aggregate_mean_to_measure_mean_own':own.aggregate_C/own[col]})
        qa.append({'population':name,'n':len(d),'minimum_stage_gt1_n':int(d.minimum_stage_number.gt(1).sum()),'minimum_stage_gt1_pct':100*d.minimum_stage_number.gt(1).mean(),'min_stage_tie_n':int(d.min_stage_tie_n.gt(1).sum()),'min_stage_tie_customer_conflict_n':int(d.min_stage_customer_unique_n.gt(1).sum()),'earliest_time_tie_n':int(d.earliest_time_tie_n.gt(1).sum()),'earliest_tie_customer_conflict_n':int(d.earliest_time_customer_unique_n.gt(1).sum()),'different_selected_record_n':int(d.min_stage_source_row_number.ne(d.earliest_time_source_row_number).sum()),'different_selected_customer_n':int(d.min_stage_customers.ne(d.earliest_time_customers).sum()),'R02_earliest_field_mismatch_n':int((~d.earliest_matches_R02_customer).sum())})
    # Compare the old selected record values by ID, not just means.
    old=pd.read_csv(R4/'data/first_stage_comparison.csv',usecols=[ID,'Restoration Stage','Number of Customers Restored'],dtype=str).set_index(ID);oldv=pd.to_numeric(old['Number of Customers Restored'].str.replace(',',''),errors='coerce');current=z.loc[old.index];mismatch=current.min_stage_customers.ne(oldv)&~(current.min_stage_customers.isna()&oldv.isna());assert len(old)==60436
    z['min_stage_customer_missing']=z.min_stage_customers.isna();z['earliest_customer_missing']=z.earliest_time_customers.isna();z['aggregate_missing']=z.aggregate_C.isna();p=Q/'data/customer_comparators_v1.parquet';z.reset_index().to_parquet(p,index=False)
    examples=z[z.min_stage_customer_unique_n.gt(1)|z.earliest_time_customer_unique_n.gt(1)].head(12).reset_index();examples['anonymous_event']=examples[ID].map(lambda x:hashlib.sha256(str(x).encode()).hexdigest()[:12]);examples=examples[['anonymous_event','minimum_stage_number','min_stage_tie_n','min_stage_customer_unique_n','earliest_time_tie_n','earliest_time_customer_unique_n','min_stage_customers','earliest_time_customers','aggregate_C','in_main']]
    table(Q/'tables/CUSTOMER_COMPARATOR_SUMMARY.csv',pd.DataFrame(rows));table(Q/'tables/CUSTOMER_SELECTION_CHECKS.csv',pd.DataFrame(qa));table(Q/'tables/CUSTOMER_TIE_EXAMPLES.csv',examples)
    result={'raw':raw,'source_rows':len(s),'stage_numeric_parse_missing_n':int(s.stage_num.isna().sum()),'stage_number_noninteger_n':int(s.stage_num.dropna().mod(1).ne(0).sum()),'R04_comparator_value_changes_n':int(mismatch.sum()),'earliest_field_all_matches_R02':True,'selection_policy':'minimum numeric stage; tie smallest persistent raw source row. Earliest valid UTC time; tie smallest persistent raw source row, matching frozen R02. Same source identity retained under row shuffle. Not true initial customers.','common_population_check':rows,'tie_check':qa,'large_table':record(p),'new_core_fits':0,'frozen_C_D_modified':False}
    # Verify tie policy against a shuffled input preserving raw source row identity.
    shuffled=nt.sample(frac=1,random_state=20260905).sort_values([ID,'source_row_number'],kind='stable').drop_duplicates(ID).set_index(ID);assert np.array_equal(shuffled.sort_index().source_row_number,nsel.sort_index().source_row_number)
    result['persistent_identity_shuffle_selection_passed']=True;put(Q/'checks/customer_comparator_audit.json',result)
    write(Q/'CUSTOMER_COMPARATOR_AUDIT.md','# R05-4客户比较：记录选择与分母\n\n只读原始阶段记录，逐事件保留原始SHA:1-based行号、最低数值阶段号、最早有效UTC时刻、各选中行的客户值与聚合C；大表本地Parquet，大小/SHA见checks/customer_comparator_audit.json。阶段编号先数值化，绝不字典序排序。\n\n'+md(pd.DataFrame(qa))+'\n## 各口径有效人口与共同人口\n\n'+md(pd.DataFrame(rows))+f'\n原R04主组最低编号客户值逐ID比较：{int(mismatch.sum())}个变化。最早时刻客户字段与R02持久source row和值全部一致。旧source_order没有进入排序是可维护性风险；当前明确以持久原行号作并列规则，打乱内存行序后选择不变。原阶段号并列是否构成结果影响以实测冲突计数为准，不能凭代码风险认定C/D聚合错误。\n\n最早时刻并列若客户数不同，当前值是冻结规则选中行的客户数，不是该时刻全部客户之和，不可称true initial。均值之比不是逐事件比值的平均；逐事件分母为0的比值没有在这里被填0。各有效n和共同有效n已分列，不将缺失跳过隐藏在比值中。冻结事件C/D定义不变，未重拟合模型。\n')
    print(json.dumps(clean(result),ensure_ascii=True),flush=True)
if __name__=='__main__':run()
