// Adapted from advisor review; no runtime access to Comments. See docs/NEW_ANALYSIS_GUIDE.md.
const fs=require("fs"),path=require("path");
const {Document,Packer,Paragraph,TextRun,HeadingLevel,ImageRun,Table,TableRow,TableCell,WidthType,AlignmentType,ShadingType,LevelFormat,PageBreak}=require("docx");
const RES=path.join(process.env.NEW_ANALYSIS_RUN,"results"), FIG=path.join(RES,"figures"), MEDIA=path.join(RES,"paper/draft_media/media");
const J=f=>JSON.parse(fs.readFileSync(f,"utf8").replace(/\bNaN\b/g,"null"));
const t2rows=J(path.join(FIG,"t2_rows.json")), worows=J(path.join(FIG,"wo_rows.json")), fragrows=J(path.join(FIG,"frag_rows.json"));
const knots=J(path.join(RES,"model_selection/knots.json")), fin=J(path.join(RES,"final_models/final_summary.json")), dd=J(path.join(RES,"final_models/district_day_fragility.json")), wo=J(path.join(RES,"weather_only/weather_only_summary.json")), ex=J(path.join(RES,"paper/paper_extras.json"));
const dec=fs.readFileSync(path.join(RES,"paper/r2_decomposition.csv"),"utf8").trim().split("\n").slice(1).map(l=>l.split(","));

// ---------- helpers
const P=(t,o={})=>new Paragraph({spacing:{after:140},alignment:AlignmentType.JUSTIFIED,...o,children:(Array.isArray(t)?t:[t]).map(x=>typeof x==="string"?new TextRun({text:x,...(o.run||{})}):new TextRun({...(o.run||{}),...x}))});
const H1=t=>new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:300,after:140},children:[new TextRun(t)]});
const H2=t=>new Paragraph({heading:HeadingLevel.HEADING_2,spacing:{before:220,after:120},children:[new TextRun(t)]});
const H3=t=>new Paragraph({heading:HeadingLevel.HEADING_3,spacing:{before:160,after:100},children:[new TextRun(t)]});
const B=t=>new Paragraph({numbering:{reference:"bul",level:0},spacing:{after:60},children:[new TextRun(t)]});
const dims=f=>{const b=fs.readFileSync(f);return [b.readUInt32BE(16),b.readUInt32BE(20)];};
const img=(f,w)=>{const sz=dims(f);return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:120,after:60},children:[new ImageRun({type:"png",data:fs.readFileSync(f),transformation:{width:w,height:Math.round(w*sz[1]/sz[0])}})]});};
const cap=t=>new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{after:220},children:[new TextRun({text:t,size:18})]});
const cell=(t,w,hdr=false)=>new TableCell({width:{size:w,type:WidthType.DXA},shading:hdr?{type:ShadingType.CLEAR,fill:"E4E8EC",color:"auto"}:undefined,margins:{top:40,bottom:40,left:70,right:70},children:[new Paragraph({children:[new TextRun({text:t,bold:hdr,size:17})]})]});
const T=(hdrs,rows,Ws)=>new Table({width:{size:Ws.reduce((a,b)=>a+b),type:WidthType.DXA},columnWidths:Ws,rows:[new TableRow({tableHeader:true,children:hdrs.map((h,i)=>cell(h,Ws[i],true))}),...rows.map(r=>new TableRow({children:r.map((v,i)=>cell(String(v),Ws[i]))}))]});
const tcap=t=>new Paragraph({alignment:AlignmentType.LEFT,spacing:{before:160,after:80},children:[new TextRun({text:t,bold:true,size:18})]});
const brk=()=>new Paragraph({children:[new PageBreak()]});
const f2=(x,d=2)=>Number(x).toFixed(d);

// ---------- numbers
const E=fin.E0, R=fin.R0c, K=knots.E0, Kb=K.two_knot.bootstrap, ddf=dd.fits, iv=dd.interpolation_validation;
const woE=wo.E0, woR=wo.R0c;
const decRow=(s,m,g)=>dec.find(r=>r[0]===s&&r[1]===m&&r[2]===g);
const pp=(s,m,g)=>f2(decRow(s,m,g)[4]*100,2), cum=(s,m,g)=>f2(decRow(s,m,g)[3]*100,2);
const dc=ex.E0_dev_conf, rc=ex.R0c_dev_conf;

// ---------- shared tables
const tblDescr=T(["Statistic","Affected customers (n=60,437)","log(1+affected customers)","Restoration duration, h (n=51,173)","log(restoration duration)"],J(path.join(RES,"paper/descriptive_rows.json")),[1700,2000,1900,2100,1900]);
const tblCov=T(["Variable","Category","Model"],[["Gust speed (piecewise-linear for exposure; linear + squared for recovery)","Weather","Both"],["Gust × mean sea level pressure","Weather","Exposure"],["Gust × 24-h precipitation","Weather","Recovery"],["Mean sea level pressure; 24-h precipitation; temperature and its square","Weather","Both"],["Log population; income deprivation rate; local–national deprivation gap; Moran's I; urban–rural indicator","Regional (district)","Both"],["log(1+affected customers), linear and squared","Event","Recovery"],["Year and month fixed effects","Temporal","Both"]],[5500,2000,1800]);
const tblFinal=T(["Margin","Term","Coef.","SE (district)","SE (district×date)","p (two-way, t₁₁₀)"],t2rows,[700,3300,1100,1200,1400,1400]);
const tblWO=T(["Margin","Term","Coef.","SE (district×date)","p (t₁₁₀)"],worows,[800,3800,1200,1600,1400]);
const tblFrag=T(["Size threshold","Occurrence","Base rate","p₀","θ (m/s)","β"],fragrows,[1700,1900,1200,1100,1100,1000]);
const tblSpec=T(["Specification (profile models use nested LAD CV)","Exposure ΔBIC versus best non-FE","Exposure CV RMSE","Recovery ΔBIC versus best non-FE","Recovery CV RMSE"],J(path.join(RES,"paper/specification_rows.json")),[4200,1300,1500,1500,1500]);
const tblDec=T(["Variable group","Exposure, all (pp)","Exposure, weather-attributed (pp)","Recovery, all (pp)","Recovery, weather-attributed (pp)"],[
["Regional + calendar",pp("all","E0","Regional + calendar"),pp("weather","E0","Regional + calendar"),pp("all","R0c","Regional + calendar"),pp("weather","R0c","Regional + calendar")],
["Non-gust weather",pp("all","E0","Non-gust weather"),pp("weather","E0","Non-gust weather"),pp("all","R0c","Non-gust weather"),pp("weather","R0c","Non-gust weather")],
["Gust",pp("all","E0","Gust"),pp("weather","E0","Gust"),pp("all","R0c","Gust"),pp("weather","R0c","Gust")],
["Affected customers","—","—",pp("all","R0c","Affected customers"),pp("weather","R0c","Affected customers")],
["Total out-of-sample R²",cum("all","E0","Gust"),cum("weather","E0","Gust"),cum("all","R0c","Affected customers"),cum("weather","R0c","Affected customers")]],[2300,1700,2000,1700,2000]);
const tblDev=T(["Term","Development (Apr 2021–Sep 2023)","Confirmation (Oct 2023–Mar 2024)","Combined"],[
["Exposure: gust below 14 m/s (per m/s)",`${f2(dc.development.gust_low.coef,3)} (${f2(dc.development.gust_low.se,3)})`,`${f2(dc.confirmation.gust_low.coef,3)} (${f2(dc.confirmation.gust_low.se,3)})`,`${f2(dc.combined.gust_low.coef,3)} (${f2(dc.combined.gust_low.se,3)})`],
["Exposure: gust ramp 14–25 m/s (per m/s)",`${f2(dc.development.gust_ramp.coef,3)} (${f2(dc.development.gust_ramp.se,3)})`,`${f2(dc.confirmation.gust_ramp.coef,3)} (${f2(dc.confirmation.gust_ramp.se,3)})`,`${f2(dc.combined.gust_ramp.coef,3)} (${f2(dc.combined.gust_ramp.se,3)})`],
["Recovery: gust squared",`${f2(rc.development.z_gust_sq.coef,3)} (${f2(rc.development.z_gust_sq.se,3)})`,`${f2(rc.confirmation.z_gust_sq.coef,3)} (${f2(rc.confirmation.z_gust_sq.se,3)})`,`${f2(rc.combined.z_gust_sq.coef,3)} (${f2(rc.combined.z_gust_sq.se,3)})`],
["n (exposure / recovery)",`${dc.development.n.toLocaleString()} / ${rc.development.n.toLocaleString()}`,`${dc.confirmation.n.toLocaleString()} / ${rc.confirmation.n.toLocaleString()}`,`${dc.combined.n.toLocaleString()} / ${rc.combined.n.toLocaleString()}`]],[3000,2200,2300,2200]);

// ---------- references
const refsRaw=J(path.join(RES,"paper/references.json"));
const newRefs=["[27] Muggeo VMR. Estimating regression models with unknown break-points. Statistics in Medicine. 2003;22(19):3055-3071.","[28] Baker JW. Efficient analytical fragility function fitting using dynamic structural analysis. Earthquake Spectra. 2015;31(1):579-599.","[29] Cameron AC, Gelbach JB, Miller DL. Robust inference with multiway clustering. Journal of Business & Economic Statistics. 2011;29(2):238-249.","[30] Porter K, Kennedy R, Bachman R. Creating fragility functions for performance-based earthquake engineering. Earthquake Spectra. 2007;23(2):471-489."];
const refPars=[...refsRaw,...newRefs].map(r=>new Paragraph({spacing:{after:80},children:[new TextRun({text:r,size:18})]}));

const numbering={config:[{reference:"bul",levels:[{level:0,format:LevelFormat.BULLET,text:"•",alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:480,hanging:240}}}}]}]};
const styles={default:{document:{run:{font:"Calibri",size:21}}}};
const props={page:{margin:{top:1134,bottom:1134,left:1134,right:1134}}};

// =====================================================================================
// EXTENDED PAPER
// =====================================================================================
const ext=[
new Paragraph({heading:HeadingLevel.TITLE,children:[new TextRun("Onset, plateau and a district-level fragility function for wind-driven power outages: three years of operational records from a UK distribution network")]}),
P("Reproduction draft generated independently from the project samples. Tables and inserted analysis figures come from this run. The inherited narrative is a historical review template: its hand-entered numbers, causal interpretations and literature claims require revision against the computed results before publication."),
P("[Author list and affiliations — to be completed]",{run:{color:"777777"}}),
H1("Abstract"),
P(`UK Power Networks recorded 60,453 weather- and asset-related outage incidents across London, the South East and the East of England between April 2021 and March 2024, including seven named storms. Event-level exposure (customers affected) and recovery (restoration time) outcomes are reconstructed from stage-level regulatory records under Ofgem's definitions, correcting a factor-of-two undercount that results from using the earliest stage alone. A specification search with district-grouped cross-validation shows that the wind response of the exposure margin is piecewise-linear rather than smooth: flat below an onset gust of 14 m/s (95% interval 13–15 m/s), rising at 0.12 log-units per m/s to 25 m/s (24–28 m/s), and constant beyond — a constraint the data do not reject and physics requires, since customers affected cannot fall with gust. On the 16% of incidents attributed to weather the response is V-shaped, because calm-wind weather incidents (lightning, flooding, snow) are large but not wind-driven, and its ramp slope of 0.08 per m/s accounts for about two-thirds of the pooled rise, the remainder being the rising share of weather faults. Restoration time rises smoothly with the square of gust and is far more predictable among weather incidents (out-of-sample R² 0.28 against 0.11). Reconstructing a panel of 121,656 district-days shows that the probability of an outage of a given size occurring in a district on a day follows a lognormal fragility function with a background rate: median gust 23–25 m/s for outages of up to 100 customers and 30 m/s for outages above 1,000, dispersion 0.24–0.44, and a floor equal to the technical-fault base rate. This is the first network-scale wind fragility function estimated from operational records, and it is directly comparable to structure-level fragility curves from simulation and testing.`),
P("Keywords: power outage; wind fragility; distribution network; piecewise regression; extreme weather; storm resilience",{run:{italics:true}}),

H1("1. Introduction"),
P("Storms are the most common cause of power disruption in Great Britain [1]. Storm Arwen in November 2021 left more than one million customers without supply [2]; three months later Storms Dudley, Eunice and Franklin struck within five days, and within the service area of UK Power Networks (UKPN) Eunice produced a peak gust of 39.4 m/s at Lewes on 18 February 2022, 1,601 weather-related outage events across 101 local authority districts and an estimated 376,712 affected customers. Such events show that outage impact does not scale in fixed proportion with wind: a given increase in gust can correspond to a negligible change in outcome under some conditions and a disproportionate one under others. Whether that response has an identifiable onset, whether it saturates, and whether it can be expressed as a fragility function of the kind used in structural engineering, are questions that bear directly on how distribution network operators (DNOs) set weather-response thresholds and pre-position restoration resources."),
P("Two literatures address adjacent versions of these questions without meeting. Statistical outage studies for hurricane- and ice-storm-affected utilities [3–6] fit regression or machine-learning models that relate weather intensity to customers affected or restoration time; they report fitted relationships but do not test for a distinguishable threshold, and they model outcomes conditional on an outage having occurred rather than the probability that one occurs. Structural engineering, by contrast, derives fragility curves — the probability of failure of a pole, tower or line as a function of wind speed — from finite-element simulation or scaled testing of a single component [7–10]. Those curves are threshold-shaped: failure probability sits near a baseline below a critical wind speed and rises steeply above it [10]. Whether a comparable threshold-shaped response exists at the scale of a whole network, where outcomes aggregate a heterogeneous population of assets, ages and local conditions, is not something either literature can answer on its own."),
P("This paper answers it using three years of continuous operational records from UKPN, a period long enough to contain both routine operating conditions and seven named storms on the same network. We ask two questions. First, what is the shape of the network's wind response — for the size of an outage once it has occurred, for the time taken to restore it, and for the probability that an outage of a given size occurs at all — and can that last quantity be written as a fragility function? Second, how much of the variation in outage outcomes does wind explain, across all incidents and among those that the operator itself attributes to weather?"),
P("Three results follow. The size of an outage responds to gust in a piecewise-linear way, with an onset at 14 m/s, a ramp to 25 m/s and a plateau beyond; a quadratic specification, of the kind used in earlier work and in an earlier version of this analysis, places a spurious turning point at 10.8 m/s that is a property of the parabola rather than of the data. Two-thirds of the ramp is recovered among weather-attributed incidents alone. And the probability that a district experiences an outage of a given size on a given day follows a lognormal fragility function in gust, with a background rate equal to the technical-fault rate, a median of 23–25 m/s and a dispersion of about 0.3 — a network-level counterpart to the component-level curves of [7–10]."),
P("Section 2 describes the data, the construction of event-level outcomes from stage-level records, and the three analysis samples. Section 3 sets out the regression framework, the specification search, the validation design and the fragility model. Section 4 reports results in five parts: the shape of the wind response on all incidents, the response on weather-attributed incidents, the explanatory weight of wind, the district-day fragility function, and checks against the named storms and an independent temporal holdout. Section 5 discusses the operational meaning of the two thresholds, the relation to structure-level fragility, restoration time, and limitations."),

H1("2. Data"),
H2("2.1 Study setting and sources"),
P("UKPN operates the distribution network across London, the South East and the East of England and reports outage incidents to Ofgem under the RIIO-ED1 and RIIO-ED2 Annex F guidance [11, 12]. The records used here cover 1 April 2021 to 31 March 2024, three complete regulatory years. Each record is a restoration stage rather than a complete incident: an incident restored in several actions is represented by several stage-level records sharing an incident reference. Weather is matched to each incident from hourly ERA5-based reanalysis via the Open-Meteo historical API [13, 14], indexed to the incident's reported coordinates and starting hour. The primary wind variable is the instantaneous gust rather than the sustained speed, following wind-engineering practice in which short-duration gust governs structural loading and failure [15, 16]. Regional covariates at the local authority district (LAD) level — population, income deprivation rate, the within-district deprivation range, spatial clustering of deprivation (Moran's I [19]) and an urban–rural indicator — are drawn from ONS sources [17, 18, 20]. Figure 1 shows the three licence areas and the spatial density of incidents, which concentrates around London with a secondary concentration on the East Anglian coast."),
img(path.join(MEDIA,"image1.png"),380),
cap("Figure 1. Study area and incident density. The three UKPN licence areas (London, South East, East of England) and the hexagonally binned density of all incidents in the analysis sample on a logarithmic count scale. Inset: location within Great Britain."),
H2("2.2 Outcome construction"),
P("Ofgem's Annex F defines two network-level measures, Customer Interruptions (CI) and Customer Minutes Lost (CML), both aggregated over a reporting period. We construct their incident-level analogues. Affected customers, Cᵢ, is the sum over the restoration stages of incident i of the customers reported at each stage, excluding stages flagged as re-interruptions so that customers are not double-counted. Restoration duration, Dᵢ, is the total span of the incident, from the earliest recorded stage start to the latest recorded stage end, including re-interruption stages. A customer-weighted duration analogous to CML was considered and rejected because it shares its weighting with Cᵢ by construction and therefore induces a spurious association between the two margins (Supplementary B). Aggregating customers across stages rather than taking the earliest stage alone raises the sample mean from 47.1 to 93.0 customers, a factor of 1.97, because incidents with more than one restoration stage are not captured by their first stage. The full processing pipeline, including boundary cases, is given in Supplementary B."),
H2("2.3 Descriptive statistics"),
P("Table 1 summarises the two outcomes and Figure 2 shows their distributions. Both are heavily right-skewed: the median incident affects two customers and the mean 93; the median restoration takes about seven hours and the maximum eight days. Log transformation removes the extreme tail that would otherwise dominate least squares but leaves visible structure. The exposure distribution has spikes at zero, one and two customers, which together account for 58% of incidents at five or fewer; this is a zero-inflated count, and Section 4.4 returns to what that implies. The recovery distribution, before cleaning, has a very tall spike at exactly one hour. Inspection shows that this spike is a placeholder: 8,661 incidents in the recovery sample interrupted no customers, and 66.5% of those carry a recorded duration of exactly 1.000 h, against 0.5% of all other incidents. A restoration time is undefined when nobody was interrupted, and these rows are removed from the recovery sample (Section 2.4). On the cleaned sample the low mode of the distribution sits at 30–35 minutes and corresponds to faults cleared by automatic reclosure."),
tcap("Table 1. Descriptive statistics of the two outcome margins in the analysis samples (recovery after exclusion of zero-customer incidents)."),tblDescr,
img(path.join(FIG,"figP2_distributions.png"),620),
cap("Figure 2. Outcome distributions on the log scale. (a) Exposure margin, all 60,437 incidents, with the spikes at zero, one and two affected customers marked. (b) Recovery margin before cleaning, showing the spike at exactly 1.000 h carried by zero-customer incidents. (c) Recovery margin after exclusion of zero-customer incidents (n = 51,173), with the automatic-reclosure mode near 0.5 h marked."),
H2("2.4 Analysis samples"),
P("UKPN records a cause code for every incident, grouped here into six categories (Supplementary A). Two — weather-related and asset-related — describe faults on the network itself; the other four (no fault found, third-party interference, human error, customer-side causes) are unrelated to wind by construction and are excluded, leaving 60,453 incidents. After weather matching and exclusion of incidents with missing regional covariates, the exposure sample contains 60,437 incidents. The recovery sample excludes incidents whose duration could not be computed or lay above the 99th percentile (59,834), and then the 8,661 zero-customer incidents described above, leaving 51,173."),
P("Three samples are analysed. The all-incident samples just described pool weather- and asset-related faults; they are the operator's population of network faults. The weather-attributed samples restrict to incidents whose cause code names weather: 9,857 exposure incidents (16.3%) and 9,254 recovery incidents. The share of incidents attributed to weather rises steeply with gust, from 7% in the 0–4 m/s band to 91% above 30 m/s, so the two samples answer different questions: the all-incident sample describes what the network as a whole experiences at a given gust, the weather-attributed sample describes the weather-caused faults alone. Finally, a district-day panel is constructed for the fragility analysis in Section 3.5: all 121,656 combinations of the 111 districts and 1,096 days in the study period, of which 34.5% contain at least one incident and 5.0% a weather-attributed one."),
P("Variance inflation factors for the continuous covariates in the final specifications are below 4 including the calendar effects (Supplementary A), so the covariate set is not collinear in the conventional sense [21]. The question of whether it over-fits is addressed by cross-validation rather than by VIFs (Section 3.3)."),

H1("3. Methods"),
H2("3.1 Regression framework"),
P("Both margins are modelled by ordinary least squares on a log-transformed outcome — log(1 + affected customers) for exposure and log(restoration duration in hours) for recovery — with weather covariates standardised on the training sample (gust, 24-h precipitation, temperature, mean sea-level pressure), unstandardised regional covariates, and additive year and month fixed effects. A log link keeps the multiplicative structure of the outcomes without the arbitrary scale of count or duration GLMs; negative-binomial, gamma and Tweedie alternatives were fitted and give the same gust coefficients in sign and significance (Supplementary H). Table 2 lists the covariates. The recovery model additionally includes log(1 + affected customers) and its square. We deliberately do not include district fixed effects. With 110 district dummies the model wins every in-sample criterion but is the worst of all candidates when whole districts are held out (cross-validated RMSE 2.10 against 1.99 for exposure and 1.50 against 1.27 for recovery), because a held-out district receives no intercept; the regional covariates capture the between-district variation that generalises."),
tcap("Table 2. Covariates in the final specifications."),tblCov,
H2("3.2 Specification search and knot estimation"),
P("The functional form of the gust response is chosen by comparison rather than assumed. Starting from a linear-weather baseline, blocks of covariates are added in a nested ladder (gust², gust×pressure, regional, calendar) and then the gust term itself is replaced by alternatives: cubic, log-gust, step dummies at gust percentiles, and piecewise-linear forms with one or two knots. For the two-knot form a physical constraint is imposed and tested: because the number of customers affected cannot fall as gust rises, the slope beyond the second knot is fixed at zero, giving a three-segment response with a free slope below the onset, a ramp between the knots, and a plateau above (a two-parameter form). The unconstrained two-hinge form, with a free slope beyond the second knot, is fitted for comparison and the constraint tested by likelihood ratio. Candidates are compared on AIC, BIC and out-of-sample RMSE under three cross-validation schemes (Section 3.3). Table 3 summarises the comparison; the full ladder is in Supplementary C."),
P("Knot locations are estimated, not chosen. For each margin and each piecewise form the residual sum of squares of the full covariate set is profiled over an exhaustive grid of knot positions in 1 m/s steps (single knot 8–30 m/s; pairs k₁ ∈ 8–20, k₂ ∈ 18–34, at least 4 m/s apart), in the spirit of segmented regression [27]. A likelihood-ratio test compares two knots against one, and a joint 95% profile region is the set of knot pairs whose likelihood-ratio statistic against the optimum is below the χ²₂ critical value. A district cluster bootstrap (500 resamples of whole districts with replacement, knots re-estimated each time) gives percentile intervals. A two-knot model is retained only if the second knot is significant at 1% and both bootstrap intervals are at most 6 m/s wide; otherwise the single profile-likelihood knot is used. Knots are re-estimated separately on the weather-attributed samples."),
tcap("Table 3. Specification comparison for the gust functional form. ΔBIC relative to the best non-fixed-effects model; cross-validated RMSE with whole districts held out."),tblSpec,
H2("3.3 Validation"),
P("Incidents on the same day and in the same district are not independent, so the primary validation holds out whole districts: five folds of 22–23 districts each, with all standardisation and knot selection repeated inside each training fold (nested cross-validation). A second scheme holds out whole years. A random incident-level split is reported for comparison only; it cannot detect the district-fixed-effects failure described in Section 3.1 and ranks that model best. The final specifications are also fitted separately on a development sample (1 April 2021 – 29 September 2023) and a confirmation sample (30 September 2023 – 31 March 2024), following the data-splitting logic of Cox [23]; the history of that split and of earlier modelling choices is in Supplementary E."),
H2("3.4 Inference"),
P("Standard errors are clustered by district and by date simultaneously [24, 29]. A single storm generates many incidents in one district on one day, and two-way clustering accommodates dependence along both dimensions; district-only clustering, which was the main inference in earlier work, understates the standard errors of the gust terms by a factor of 1.3–2.3. p-values use a t reference distribution with 110 degrees of freedom (the number of district clusters minus one)."),
H2("3.5 District-day fragility"),
P("The regression models describe the size and duration of an outage conditional on one having occurred. A fragility function describes the probability that an outage of at least a given size occurs, and needs a denominator of exposure units rather than incidents. We define the exposure unit as a district-day and the damage states by the largest outage in the district on that day: any incident, more than 5, more than 100 and more than 1,000 customers, either from any cause or from a weather-attributed cause. The package of incident records contains no weather for district-days without incidents, so a daily district gust is interpolated to each district centroid from that day's incident-level gust observations by Gaussian-kernel inverse-distance weighting with a 40 km bandwidth (every date has at least 15 incidents in at least 13 districts, and incident gusts within a district-day vary by about 1.8 m/s). Leaving each district's own incidents out, the interpolated gust reproduces the observed district-day mean with RMSE 2.2 m/s, correlation 0.85 and no bias. This is a documented proxy for a gridded daily maximum, which would be preferable."),
P("The fragility function is the lognormal form standard in earthquake and wind engineering [28, 30], augmented with a gust-independent background rate p₀ because technical faults occur in any weather: P(DS ≥ k | g) = p₀ + (1 − p₀)Φ((ln g − ln θ)/β), with median θ and dispersion β, fitted by binomial maximum likelihood on the 121,656 district-days. A gust × precipitation surface is fitted as a probit with an interaction term and log population as a covariate, and monotonicity in gust is checked numerically over the observed domain."),

H1("4. Results"),
H2("4.1 The wind response is piecewise, not smooth"),
P("Figure 3 shows, for each margin, the mean residual of the full model fitted without any gust term, averaged within gust bands. These binned partial residuals owe nothing to a functional form and are the primary evidence for the shape of the response. For exposure the response is flat or slightly declining up to about 14 m/s, rises steeply between 16 and 26 m/s, and flattens above 26 m/s (band means 0.93, 1.03, 0.89 in the 23–26, 26–30 and 30–45 m/s bands). For recovery the response is flat to about 16 m/s and rises without an obvious plateau. Overlaid on the residuals are the quadratic, cubic and piecewise-linear fits. The quadratic misses the exposure response in both tails: it over-predicts by 0.3 log-units at 20–26 m/s and under-predicts by 0.8 above 30 m/s (Supplementary G), and its vertex at 10.8 m/s is pulled left of the empirical minimum (12–14 m/s) by the dense mass of calm-weather incidents. The cubic bends over but then predicts a decline. The piecewise forms show no residual bias in any band."),
img(path.join(FIG,"fig2_gust_response.png"),620),
cap("Figure 3. Wind response of the two margins, all incidents. Points: binned partial residuals (full model without gust terms) with 95% CI. Lines: fitted gust responses of the quadratic, cubic, piecewise-linear and log-gust specifications, shifted by a constant to the residual scale. Vertical lines: the vertex of the quadratic (10.8 m/s) and the estimated knots (14 and 25 m/s)."),
P(`The knot estimation (Figure 4) makes this precise. For exposure an unconstrained two-hinge model at 14 and 26 m/s beats the quadratic by ΔBIC = −129 and the single-knot model by a likelihood ratio of 44 (p ≈ 2×10⁻¹⁰); its slope beyond the second knot is −0.155 against +0.146 below it, a net −0.009 ± 0.03 per m/s, indistinguishable from zero. Imposing the plateau — no change in affected customers beyond the second knot — is not rejected (likelihood ratio 1.5, p = 0.22), lowers BIC by a further 10 for one fewer parameter, and gives identical nested cross-validated error (1.9850 against 1.9851). The three-segment plateau form is therefore adopted, with knots re-profiled at 14 and 25 m/s: the onset knot is located at 13–14 m/s by the profile region and 13–15 m/s by the bootstrap; the plateau knot at 24–27 m/s and 24–28 m/s. Knots re-estimated inside each cross-validation fold fall at 13–14 and 24–28 m/s, and the nested-CV error of the plateau form (1.9850) improves on the quadratic (1.9872 with temperature²; 1.9887 without), so the gain survives selection without sight of the test districts. For recovery a second knot is nominally significant (p ≈ 2×10⁻⁴) but its first knot is not identified — the bootstrap interval spans 8–16 m/s — because the recovery response is flat below 17 m/s and there is nothing for a first knot to locate; a single knot at 17 m/s is BIC-preferred over the quadratic (Δ = −11) but gives identical out-of-fold error. The plateau form was also tested for recovery: its second knot lands at 33 m/s, at the edge of the search grid, with a bootstrap interval (29–34 m/s) that hits the boundary, and nested cross-validated error is indistinguishable from the quadratic (1.1501 against 1.1504); on weather-attributed incidents the same holds (knot 33 m/s, 1.2478 against 1.2476). Restoration time therefore rises through the observed gust range and any flattening lies above 30 m/s, where the record is too thin to locate it. The quadratic is therefore retained for recovery and the plateau form adopted for exposure.`),
img(path.join(FIG,"fig6_knot_estimation.png"),620),
cap("Figure 4. Knot estimation. Left: BIC profile for a single knot with the quadratic as reference. Centre: likelihood-ratio surface for two knots; white contour is the joint 95% region and the star the optimum. Right: district-bootstrap distributions of the two knots (B = 500; unconstrained two-hinge form, for which the second knot is 26 m/s; the plateau form re-profiles it at 25 m/s with bootstrap interval 24–28 m/s)."),
P(`Table 4 reports the final specifications with two-way clustered inference. The exposure model adds temperature² (both cold and hot extremes raise affected customers) to the plateau gust response and retains gust × pressure, which is marginal (p = ${t2rows.find(r=>r[1].startsWith("Gust × pressure"))[5]}). Below the onset affected customers decline slightly with gust (${t2rows.find(r=>r[1].startsWith("Gust below"))[2]} per m/s), the composition effect of technical faults at calm winds; between 14 and 25 m/s they rise by ${t2rows.find(r=>r[1].startsWith("Gust ramp"))[2]} log-units, about 13%, per m/s of gust, a factor of ${f2(Math.exp(0.1215*11),1)} across the ramp; above 25 m/s they are constant by construction, and the data do not object. The recovery model drops gust × pressure, which is not significant in any specification, and adds temperature² and gust × precipitation; the latter is negative — wet storms are restored faster, an effect that recurs in the fragility surfaces of Section 4.4. Relative to the previous quadratic specifications the final models improve adjusted R² from ${f2(E.paper_adj_r2,4)} to ${f2(E.adj_r2,4)} (exposure) and ${f2(R.paper_adj_r2,4)} to ${f2(R.adj_r2,4)} (recovery, same cleaned sample), and district-grouped CV RMSE from ${f2(E.paper_cv_lad,4)} to ${f2(E.final_cv_lad,4)} and ${f2(R.paper_cv_lad,4)} to ${f2(R.final_cv_lad,4)}. Figure 5 shows the final gust responses with their two-way 95% bands and the out-of-fold calibration of final against previous models.`),
tcap("Table 4. Final specifications, all incidents: weather and customer terms. Full coefficient tables in Supplementary F."),tblFinal,
img(path.join(FIG,"fig11_final_models.png"),600),
cap("Figure 5. Final models. Left: gust response at mean covariates with district×date-clustered 95% bands, against the previous quadratic. Right: mean observed against mean out-of-fold predicted value within predicted-value ventiles under district-grouped cross-validation, final and previous specifications."),
P("Two features of the recovery model deserve comment. On the cleaned sample the customer-count terms are both negative (Table 4): among incidents that interrupted someone, larger incidents are restored proportionally faster, consistent with dispatch prioritisation and contrary to the independence reported for US utilities [26]. And the calibration of the recovery model is now clean across its range (Figure 5, lower right); the systematic over-prediction of the shortest events reported in an earlier version of this analysis was entirely due to the placeholder rows."),

H2("4.2 The same response among weather-attributed incidents"),
P(`Restricting to incidents the operator attributes to weather removes the composition effect — the rising share of weather faults with gust — and asks what the weather faults themselves do. Figure 6 and Table 5 give the answer. For exposure the response is V-shaped. Weather incidents at 0–6 m/s are lightning, flooding and snow events: large, but not wind-driven, so gust is the wrong intensity measure for them. The response falls to a minimum at 11 m/s (knots re-profiled on the subsample: 11 and 24 m/s; second-knot p ≈ 2×10⁻⁷) and rises at ${worows.find(r=>r[0]==="E0"&&r[1].startsWith("Gust ramp"))[2]} log-units per m/s to 24 m/s. That is about two-thirds of the pooled ramp slope (0.121), so roughly two-thirds of the pooled rise in affected customers between the onset and the plateau is the vulnerability of weather-caused faults and one-third is composition, the rising share of weather faults with gust; composition also shifts the pooled onset from 11 to 14 m/s, because the technical-fault mass pulls the first knot to the right. The plateau constraint is marginally rejected on this subsample (p = 0.011), entirely because of the 30–45 m/s band, which holds about 300 weather incidents and sits below the plateau with a wide interval; the constraint is imposed on physical grounds and the unconstrained fit is given in Supplementary C. The quadratic is mis-specified on this sample — gust² has p = 0.52 while the linear term is positive — because it is trying to fit a V, which is why an earlier analysis found a "physically impossible" turning point here. Temperature² is much stronger among weather incidents (${worows.find(r=>r[0]==="E0"&&r[1].startsWith("Temperature squared"))[2]}, p < 10⁻⁴), consistent with cold-snap and heat-wave incidents sitting in the calm-wind part of the subsample.`),
img(path.join(FIG,"fig13_weather_only.png"),620),
cap("Figure 6. Wind response on weather-attributed incidents only. Black: binned partial residuals with 95% CI. Green: three-segment plateau fit with knots re-profiled on the subsample and two-way clustered 95% band. Red dashed: quadratic on the same subsample. Grey dotted: the all-incident final model, for comparison."),
tcap("Table 5. Final specifications fitted to weather-attributed incidents only: weather and customer terms."),tblWO,
P(`Recovery time behaves differently. It is far more predictable among weather incidents — adjusted R² ${f2(woR.fits.final.adj_r2,2)} against ${f2(R.adj_r2,2)} on all incidents — because the technical-fault noise is removed and because storm timing is absorbed by the calendar effects. The quadratic and a single hinge at 11 m/s are equivalent, gust × precipitation is again negative (${worows.find(r=>r[0]==="R0c"&&r[1].startsWith("Gust × precip"))[2]}, p = ${worows.find(r=>r[0]==="R0c"&&r[1].startsWith("Gust × precip"))[4]}), and the binned residuals flatten above about 25 m/s in a way neither smooth form captures; with about 900 weather incidents above 26 m/s this is suggestive of the same saturation seen for exposure rather than established.`),

H2("4.3 How much wind explains"),
P(`The results so far establish the shape of the wind response. They do not say how much of the variation in outcomes wind accounts for, and the two questions have different answers. Table 6 and Figure 7 decompose the out-of-sample R² of the final specifications, under district-grouped cross-validation, by adding blocks of covariates in sequence: regional and calendar effects, non-gust weather, gust, and (recovery only) affected customers. On all incidents gust contributes ${pp("all","E0","Gust")} percentage points to the exposure margin out of a total of ${cum("all","E0","Gust")}%, and ${pp("all","R0c","Gust")} points to the recovery margin, where affected customers contributes ${pp("all","R0c","Affected customers")} points and the total is ${cum("all","R0c","Affected customers")}%. Among weather-attributed incidents the total rises to ${cum("weather","E0","Gust")}% for exposure and ${cum("weather","R0c","Affected customers")}% for recovery, and gust's contribution rises to ${pp("weather","E0","Gust")} and ${pp("weather","R0c","Gust")} points. For the recovery margin the ordering of gust and affected customers is reversed relative to their pooled values once only weather incidents are considered, but the largest single block on the weather sample is the calendar effects (${pp("weather","R0c","Regional + calendar")} points), which absorb storm timing: restoration times during the named storms are long for reasons — crew competition, access, sequential faults — that the month dummies pick up and the weather covariates do not.`),
tcap("Table 6. Marginal out-of-sample R² (percentage points) by variable group, final specifications, district-grouped cross-validation."),tblDec,
img(path.join(FIG,"figP1_r2_decomposition.png"),600),
cap("Figure 7. Marginal out-of-sample R² by variable group, both margins and both samples."),
P("The conclusion is the one earlier work reached with different numbers: wind has a real and sharply nonlinear effect on outage size, but the size of an individual outage is dominated by factors outside the record — network configuration, asset condition, protection settings. The models in Sections 4.1–4.2 estimate the shape of the weather response, not the size of outages. The quantity that wind does predict well is the one the next section estimates."),

H2("4.4 A district-day fragility function"),
P("The exposure regressions are severity-given-occurrence models, and Section 4.2 shows why their exceedance probabilities cannot be read as fragility curves: conditional on an incident, the probability of exceeding 100 customers is 0.40 at calm winds, 0.29 at 12–18 m/s and 0.48 above 23 m/s, a V rather than a monotone function, because the calm-wind incidents are large non-wind events (Supplementary H gives the incident-level lognormal fits, which degenerate for exposure). The district-day panel changes the denominator from incidents to exposure units and gives a fragility function in the proper sense. Figure 8 shows it and Table 7 gives the parameters."),
img(path.join(FIG,"fig12_district_day_fragility.png"),640),
cap("Figure 8. District-day exposure fragility. Left: probability that a district experiences at least one incident of the given size on a day, any cause. Centre: the same for weather-attributed incidents. Points: empirical frequencies by gust band with 95% CI; lines: background-rate lognormal fits. Right: probability of at least one outage above 100 customers as a function of gust and 24-h precipitation, at the median district (probit with interaction; white contours at 0.1, 0.25, 0.5)."),
tcap("Table 7. Background-rate lognormal fragility parameters per district-day, P = p₀ + (1 − p₀)Φ((ln g − ln θ)/β)."),tblFrag,
P(`Three results. First, the empirical frequencies are monotone in gust, as a fragility should be, and the background-rate lognormal fits them closely; a plain lognormal without p₀ underfits badly because technical faults occur in any weather. Second, the medians are tightly grouped: θ = ${ddf.any_gt0.lognormal.theta.toFixed(1)}, ${ddf.any_gt5.lognormal.theta.toFixed(1)} and ${ddf.any_gt100.lognormal.theta.toFixed(1)} m/s for any incident, more than 5 and more than 100 customers, and ${ddf.any_gt1000.lognormal.theta.toFixed(1)} m/s for more than 1,000, with β between ${Math.min(...Object.values(ddf).map(v=>v.lognormal.beta)).toFixed(2)} and ${Math.max(...Object.values(ddf).map(v=>v.lognormal.beta)).toFixed(2)}. The network's weather response switches on at about 23 m/s (Beaufort 9) whatever the size threshold, and the thresholds differ mainly in their floors, which reproduce the technical-fault base rates almost exactly (p₀ = ${ddf.any_gt0.lognormal.p0.toFixed(3)} against a base rate of ${ddf.any_gt0.base_rate.toFixed(3)} for any incident; ${ddf.any_gt100.lognormal.p0.toFixed(3)} against ${ddf.any_gt100.base_rate.toFixed(3)} for more than 100). Third, the weather-attributed curves for at least one, more than 5 and more than 100 customers nearly coincide (θ = ${ddf.wthr_gt0.lognormal.theta.toFixed(1)}, ${ddf.wthr_gt5.lognormal.theta.toFixed(1)}, ${ddf.wthr_gt100.lognormal.theta.toFixed(1)} m/s): once a storm produces a weather outage in a district, that outage is usually large, which is the network-level counterpart of the flat-then-rising incident-level curves of Section 4.2. The plateau knot of the incident-level exposure model, 25 m/s, sits where the district-day curves pass through P ≈ 0.5: beyond it most districts already have an outage and the marginal incident adds little to the count.`),
P(`The gust × precipitation surface (Figure 8, right) is monotone in gust over ${(dd.surface_gt100.frac_domain_monotone_gust*100).toFixed(0)}% of the observed domain, and precipitation attenuates the wind effect: at a given gust, wet days have a lower probability of a large outage than dry ones. The same sign appears in the recovery regressions (Section 4.1). Whether this reflects lower conductor loading in rain-bearing systems, better forecasting of wet storms, or a difference in the type of storm (convective versus frontal) cannot be resolved from these data.`),

H2("4.5 Storm-period and temporal checks"),
P(`Seven named storms — Arwen, Dudley, Eunice, Franklin, Babet, Ciarán and Henk — fall within the study period and span 27 days, 2.5% of the period, during which 8.2% of incidents and 14.7% of affected customers occurred. Predictions of the final models for the storm-period incidents (Supplementary I, reproducing the earlier storm-by-storm comparison) show the pattern expected from Section 4.3: the exposure model tracks the mean but not individual incidents, and the recovery model's fitted–observed correlation across all seven storms is positive and significant within the duration range it was fitted to. The independent temporal check is more informative with the piecewise specification than it was with the quadratic (Table 8). Fitted separately on the development and confirmation samples, the ramp slope of the exposure margin is ${f2(dc.development.gust_ramp.coef,3)} ± ${f2(dc.development.gust_ramp.se,3)} and ${f2(dc.confirmation.gust_ramp.coef,3)} ± ${f2(dc.confirmation.gust_ramp.se,3)} log-units per m/s — higher in the confirmation sample, which is a single autumn and winter and contains the storms Babet, Ciarán and Henk, but of the same order and the same sign — and the recovery quadratic term is ${f2(rc.development.z_gust_sq.coef,3)} and ${f2(rc.confirmation.z_gust_sq.coef,3)}. The instability of the quadratic's turning point between these two samples, which occupied a substantial part of the earlier analysis, does not arise for the plateau form because no ratio of coefficients is involved.`),
tcap("Table 8. Gust terms of the final specifications fitted separately on the development and confirmation samples (two-way clustered SE in parentheses)."),tblDev,

H1("5. Discussion"),
H2("5.1 Two operational numbers"),
P("The exposure margin has an onset at 14 m/s and a plateau from 25 m/s, both estimated with intervals rather than chosen, and both stable under district-grouped resampling, nested cross-validation and an independent temporal split. Between them, affected customers rise by about 13% per m/s of gust, a factor of 3.8 across the ramp; beyond 25 m/s they do not rise further, a constraint the unconstrained fit does not reject and physics requires. The onset corresponds to the top of Beaufort force 6 to 7 — the wind at which loose material, small branches and unsecured objects begin to move — and the plateau to Beaufort 10, storm force. Below the onset, wind is not what determines the size of an outage; above the plateau knot, the count of customers affected in a district is bounded by network topology and further gust does not increase it, even though restoration time keeps growing. An earlier version of this analysis reported a critical wind speed of 10.8 m/s from a quadratic fit. That number is the vertex of a parabola forced through a response with a floor and a plateau, and its movement between samples — which prompted extensive discussion of turning-point confidence intervals — was a symptom of mis-specification rather than of a fragile finding. We recommend that neither it nor any quadratic turning point be used as a planning reference."),
H2("5.2 Composition and vulnerability"),
P("The share of incidents attributed to weather rises from 7% at calm to 91% above 30 m/s, so any pooled analysis of outage records mixes a changing cause composition with the vulnerability of the network to wind. Two results separate them. The weather-attributed incidents alone show two-thirds of the pooled ramp slope, so most of the rise is vulnerability and the rest composition; and the district-day fragility function has a floor exactly equal to the technical-fault rate, so the composition is captured by p₀ and the lognormal term is the weather-driven part. The calm-wind weather incidents — lightning, flooding, snow — are the one group for which gust is simply the wrong intensity measure, and they are what makes the incident-conditional exceedance V-shaped."),
H2("5.3 Relation to structure-level fragility curves"),
P("The introduction cited fragility curves for transmission towers and distribution poles derived from simulation and testing [7–10], which express the probability of failure of a single component as a lognormal function of wind speed. The district-day function estimated here has the same form and can be read alongside them: a median gust of 23–25 m/s for an outage of up to 100 customers in a district on a day, dispersion 0.3, and a floor for non-weather faults. Its median is well below the medians typically reported for the structural failure of individual poles or towers, which is as it should be: a district contains thousands of spans, conductors, insulators and vegetation-clearance margins, any one of which can fail, so the network-level median is an extreme-value quantity of the component distribution. The function is directly usable in a hazard-consistent risk calculation — convolved with a district gust hazard curve it gives the annual frequency of an outage of a given size per district — which the incident-level regressions are not."),
H2("5.4 Restoration time"),
P("Restoration time rises smoothly with the square of standardised gust, from about 5 hours at mean gust to 12 hours at 30 m/s at mean covariates, and is much better predicted among weather incidents (R² 0.28) than overall (0.11). Unlike affected customers it does not plateau within the observed range: a three-segment fit places the upper knot at 33 m/s, at the edge of the data, with no improvement in out-of-sample error. The asymmetry is physical — customer count is bounded by network topology once most districts have an outage, whereas restoration time is bounded by crew capacity and access, which bind only in the most extreme storms — and the district-day fragilities show the same contrast, the exposure curves crossing P = 0.5 at 25 m/s while the ≥ 12 h and ≥ 48 h restoration curves keep rising to 40 m/s. Three secondary findings bear on operations. Larger incidents are restored proportionally faster once the placeholder rows are removed, consistent with dispatch prioritisation and contrary to the independence found for US utilities [26]. Wet storms are restored faster than dry ones at the same gust. And the low mode of the duration distribution, at 30–35 minutes, is automatic reclosure; weather alone cannot separate those faults from sustained ones, and a reclosure flag, if the operator's records carry one, would be the single most useful addition to the recovery model."),
H2("5.5 Limitations and further work"),
P("The district gust used for the fragility function is interpolated from the incident locations of the same day; it is validated against held-out districts (RMSE 2.2 m/s, r = 0.85) but a gridded daily maximum from the reanalysis would remove the dependence on incident coverage and should replace it. The incident-level models use public weather and demographic covariates and no asset information — age, material, construction type, vegetation management — any of which could explain more of the variation in outage size than the covariates used here. The confirmation sample covers six months of a single autumn and winter. The fragility function is estimated for a single DNO over three years and the curve above 30 m/s rests on a few hundred district-days; its extension to other networks is a question of transferability that the method, but not the numbers, supports. Finally, the models describe conditional associations in operational records, not mechanisms: connecting the onset, the plateau and the rain attenuation to specific physical or operational processes is the natural next step, as is the convolution of the fragility function with a district-level gust hazard to produce annual exceedance frequencies."),
P("The approach — reconstructing event-level outcomes from stage-level regulatory records, estimating rather than assuming the shape of the weather response, and moving from incidents to exposure units to obtain a fragility function — is not specific to UKPN and can be applied to any distribution operator that reports at stage level under a comparable framework."),

H1("Data and code availability"),
P("The analysis samples, the district-day panel and all scripts (specification search, knot estimation, final models, weather-attributed regressions, fragility fitting, figure generation) are provided in the accompanying package STST2603_review. [Deposit DOI to be added.]"),
H1("Supplementary Information (contents)"),
B("A. Data dictionary, cause-code grouping, covariate distributions and VIFs"),B("B. Outcome-construction pipeline and the rejected customer-weighted duration"),B("C. Full specification ladder, both samples (12 specifications × 2 margins), with AIC, BIC and three cross-validation schemes"),B("D. Knot profiles, bootstrap distributions and nested-CV fold knots"),B("E. Development/confirmation split history"),B("F. Full coefficient tables, district-only and two-way clustered"),B("G. Predicted-versus-observed and calibration figures; residual bias by gust band"),B("H. Alternative links (negative binomial, gamma, Tweedie), ordinal-logit and incident-level lognormal exceedance curves, and why they are not fragility functions"),B("I. Storm-by-storm predicted-versus-observed comparison"),
H1("References"),...refPars];

// =====================================================================================
// NATURE COMMUNICATIONS EXTRACT
// =====================================================================================
const nc=[
new Paragraph({heading:HeadingLevel.TITLE,children:[new TextRun("A network-scale wind fragility function for electricity distribution outages from three years of operational records")]}),
P("Reproduction draft generated independently from the project samples. Tables and inserted analysis figures come from this run. The inherited narrative is a historical review template: its hand-entered numbers, causal interpretations and literature claims require revision against the computed results before publication."),
P("[Author list and affiliations — to be completed]. Nature Communications format: main text ≈ 3,300 words, five figures and one table; Methods ≈ 1,900 words; Supplementary Information from the extended paper.",{run:{color:"777777"}}),
H1("Abstract"),
P("Wind is the leading cause of power disruption in temperate networks, yet the wind vulnerability of a whole distribution network has only been described by smooth statistical fits to outage records or by fragility curves of single poles and towers from simulation. Here we use three years of stage-level regulatory records from UK Power Networks — 60,453 network-fault incidents including seven named storms — to estimate the shape of the wind response rather than assume it. Outage size is flat below an onset gust of 14 m/s (95% interval 13–15), rises by 13% per m/s to 25 m/s (24–28), and is constant beyond — a constraint the data do not reject; two-thirds of that rise is found on the 16% of incidents the operator attributes to weather alone. Reconstructing 121,656 district-days, we show that the probability that a district experiences an outage of a given size on a day follows a lognormal fragility function in gust with a background rate equal to the technical-fault rate: median 23–25 m/s for outages of up to 100 customers, 30 m/s above 1,000, dispersion about 0.3. This is a network-level counterpart of component fragility curves and is directly usable with a wind hazard to obtain annual outage-exceedance frequencies."),

H1("Introduction"),
P("Storms are the most common cause of power disruption in Great Britain [1]; Storm Arwen in 2021 left more than a million customers without supply [2], and Storm Eunice three months later produced the highest gust in the record examined here, 39.4 m/s, with 1,601 weather-related outage events on one network in a day. Two literatures describe what wind does to a distribution network, and they do not meet. Statistical outage studies for hurricane- and ice-storm-affected utilities [3–6] fit regression or machine-learning models relating weather intensity to customers affected or restoration time; they report smooth fitted curves, do not test for a threshold, and model the size of an outage conditional on one having occurred. Structural engineering derives fragility curves — the probability that a pole, tower or line fails as a function of wind speed — from finite-element simulation or scaled testing of a single component [7–10]; those curves are threshold-shaped, with failure probability near a baseline below a critical wind speed and rising steeply above it. Whether a threshold-shaped response exists at the scale of a whole network, and whether the probability of an outage at the network scale can be written as a fragility function at all, has not been established from operational records."),
P("We answer both questions with three years of continuous records from UK Power Networks (UKPN), which serves London, the South East and the East of England, a period containing routine operation and seven named storms on the same network. Rather than assuming a functional form, we search over specifications with whole districts held out, estimate the location of any thresholds with intervals, and separate the changing mix of weather and technical faults from the vulnerability of the network to wind. We then move the unit of analysis from the incident to the district-day to obtain the probability of occurrence that the incident-level literature cannot provide."),

H1("Results"),
H2("Outage size responds to wind in a piecewise, not smooth, way"),
P("Event-level outcomes — customers affected and restoration duration — are reconstructed from 116,064 stage-level records under Ofgem's definitions (Methods), correcting a factor-of-two undercount that results from using the earliest stage of each incident alone. Both are modelled on the log scale with weather, district and calendar covariates, and the shape of the gust term is chosen by comparison among quadratic, cubic, logarithmic, step and piecewise-linear forms on out-of-sample error with whole districts held out. Figure 1 shows the binned partial residuals of the full model fitted without any gust term, which owe nothing to a functional form, together with the fitted candidates. Outage size is flat or slightly declining to about 14 m/s, rises steeply to 26 m/s, and flattens above; restoration time is flat to about 16 m/s and rises without a plateau. A quadratic — the form used by earlier statistical studies and by an earlier version of this analysis — over-predicts by 0.3 log-units at 20–26 m/s and under-predicts by 0.8 above 30 m/s, and its vertex at 10.8 m/s is pulled left of the empirical minimum by the dense mass of calm-weather incidents. An unconstrained two-hinge form with knots estimated by profile likelihood at 14 and 26 m/s beats the quadratic by ΔBIC = −129 and shows no residual bias in any gust band; its net slope beyond 26 m/s is −0.009 ± 0.03 per m/s. Because affected customers cannot fall as gust rises, we impose a plateau beyond the second knot: the constraint is not rejected (likelihood ratio 1.5, p = 0.22), lowers BIC by a further 10, and re-profiles the knots at 14 and 25 m/s, with a district cluster bootstrap placing the onset at 13–15 m/s and the plateau at 24–28 m/s (Supplementary Fig. 1). Nested cross-validated error with knots re-selected inside each training fold improves on the quadratic (1.9850 against 1.9872). Between the knots, affected customers rise by 13% per m/s of gust, a factor of 3.8 across the ramp (Table 1). Fitted separately on the first 30 and the last 6 months of the record, the ramp slope is 0.100 ± 0.014 and 0.149 ± 0.020 log-units per m/s — higher in the confirmation winter, which contains three named storms, but of the same order; the instability that the quadratic's turning point showed between the same two samples does not arise because no ratio of coefficients is involved. Restoration time is adequately described by the square of gust: a second knot is nominally significant but not identified, because the response is flat below 17 m/s, and a plateau form places its upper knot at the edge of the observed gust range (33 m/s, bootstrap 29–34) with no gain in cross-validated error — exposure saturates within the data, recovery does not."),
img(path.join(FIG,"fig2_gust_response.png"),620),
cap("Fig. 1 | The wind response of outage size and restoration time is piecewise. Points: mean residual of the full model fitted without gust terms, within gust bands, with 95% CI, for all 60,437 (exposure) and 51,173 (recovery) incidents. Lines: fitted gust responses of the quadratic, cubic, piecewise-linear and log-gust specifications on the same scale. Vertical lines mark the quadratic's vertex (10.8 m/s) and the estimated knots (14 and 25 m/s)."),
tcap("Table 1 | Final specifications, all incidents: weather and customer terms, standard errors clustered by district and date, p-values from t with 110 degrees of freedom."),tblFinal,

H2("The same slope among weather-attributed incidents"),
P(`Only 16% of incidents are attributed by the operator to weather, and that share rises from 7% in the 0–4 m/s band to 91% above 30 m/s, so a pooled response mixes a changing cause composition with the network's vulnerability. Refitting on the 9,857 weather-attributed exposure incidents with knots re-estimated on the subsample (Fig. 2) separates the two. The response is V-shaped: weather incidents at calm winds are lightning, flooding and snow events, large but not wind-driven, so gust is the wrong intensity measure for them; the response bottoms at 11 m/s and then rises at ${worows.find(r=>r[0]==="E0"&&r[1].startsWith("Gust ramp"))[2]} log-units per m/s to a plateau at 24 m/s (knots re-profiled on the subsample). That is two-thirds of the pooled ramp slope of 0.121: most of the pooled rise is the vulnerability of weather-caused faults and the remainder is composition, which also shifts the pooled onset from 11 to 14 m/s by adding technical-fault mass at low gusts. The quadratic is not merely sub-optimal on this sample but mis-specified (gust² p = 0.52), which is why an earlier analysis found a physically impossible turning point here. Restoration time is far more predictable among weather incidents (out-of-sample R² 0.28 against 0.11 on all incidents) and rises faster on dry days than wet ones at the same gust (gust × precipitation ${worows.find(r=>r[0]==="R0c"&&r[1].startsWith("Gust × precip"))[2]}, p = ${worows.find(r=>r[0]==="R0c"&&r[1].startsWith("Gust × precip"))[4]}).`),
img(path.join(FIG,"fig13_weather_only.png"),620),
cap("Fig. 2 | The wind response on weather-attributed incidents only. Black: binned partial residuals with 95% CI (n = 9,857 exposure; 9,254 recovery). Green: three-segment plateau fit with knots re-profiled on the subsample and district×date-clustered 95% band. Red dashed: quadratic on the same subsample. Grey dotted: the all-incident model of Fig. 1."),

H2("Wind explains little of outage size and much of outage occurrence"),
P(`Under district-grouped cross-validation, gust adds ${pp("all","E0","Gust")} percentage points to the out-of-sample R² of outage size on all incidents, out of a total of ${cum("all","E0","Gust")}%, and ${pp("weather","E0","Gust")} points out of ${cum("weather","E0","Gust")}% among weather incidents (Supplementary Fig. 2). The size of an individual outage is dominated by network configuration, asset condition and protection settings that the record does not contain, and the incident-level models estimate the shape of the wind response, not the size of outages. The quantity wind does predict is whether an outage occurs, and the incident-level record cannot estimate it, because its exceedance probabilities are conditional on an incident: given that one occurred, the probability of exceeding 100 customers is 0.40 at calm winds, 0.29 at 12–18 m/s and 0.48 above 23 m/s, a V rather than a monotone function (Supplementary Fig. 3). A fragility function needs a denominator of exposure units.`),

H2("A district-day fragility function"),
P(`We reconstruct all 121,656 combinations of the 111 districts and 1,096 days in the record, of which 34.5% contain at least one incident and 5.0% a weather-attributed one, and assign each district-day a gust interpolated from that day's incident locations (leave-district-out RMSE 2.2 m/s, r = 0.85; Methods). The probability that a district experiences an outage of at least a given size on a day is then monotone in gust (Fig. 3) and is closely fitted by a lognormal fragility function with a background rate, P = p₀ + (1 − p₀)Φ((ln g − ln θ)/β). The medians are tightly grouped — ${ddf.any_gt0.lognormal.theta.toFixed(1)}, ${ddf.any_gt5.lognormal.theta.toFixed(1)} and ${ddf.any_gt100.lognormal.theta.toFixed(1)} m/s for any incident, more than 5 and more than 100 customers, and ${ddf.any_gt1000.lognormal.theta.toFixed(1)} m/s for more than 1,000 — with dispersions of ${Math.min(...Object.values(ddf).map(v=>v.lognormal.beta)).toFixed(2)}–${Math.max(...Object.values(ddf).map(v=>v.lognormal.beta)).toFixed(2)}, and the floors reproduce the technical-fault base rates (p₀ = ${ddf.any_gt0.lognormal.p0.toFixed(3)} against ${ddf.any_gt0.base_rate.toFixed(3)} for any incident; ${ddf.any_gt100.lognormal.p0.toFixed(3)} against ${ddf.any_gt100.base_rate.toFixed(3)} for more than 100). The network's weather response switches on at about 23 m/s, Beaufort 9, whatever the size threshold, and the thresholds differ mainly in their floors. For weather-attributed occurrence the curves for at least one, more than 5 and more than 100 customers nearly coincide (θ = ${ddf.wthr_gt0.lognormal.theta.toFixed(1)}, ${ddf.wthr_gt5.lognormal.theta.toFixed(1)}, ${ddf.wthr_gt100.lognormal.theta.toFixed(1)} m/s): once a storm produces a weather outage in a district, that outage is usually large. The plateau knot of the incident-level model, 25 m/s, is where the district-day curves pass through P ≈ 0.5, beyond which most districts already have an outage and the marginal incident adds little. A gust × precipitation surface (Fig. 4) is monotone in gust over ${(dd.surface_gt100.frac_domain_monotone_gust*100).toFixed(0)}% of the observed domain and shows that rain attenuates the wind effect, the same sign found for restoration time.`),
img(path.join(FIG,"fig12_district_day_fragility.png"),640),
cap("Fig. 3 | District-day exposure fragility. Left: probability that a district experiences at least one incident of the given size on a day, any cause. Centre: weather-attributed incidents. Points: empirical frequencies by gust band with 95% CI over 121,656 district-days; lines: background-rate lognormal fits. Right: probability of at least one outage above 100 customers as a function of gust and 24-h precipitation at the median district, probit with interaction; white contours at 0.1, 0.25 and 0.5. (In the submitted version the right panel becomes Fig. 4.)"),
tcap("Table 2 | Fragility parameters per district-day (in the submitted version, merged into Fig. 3 as an inset)."),tblFrag,

H1("Discussion"),
P("Two numbers summarise the incident-level results and are, we argue, the operational thresholds a distribution operator should carry: an onset at 14 m/s (Beaufort 7, the wind at which loose material and small branches begin to move) below which wind does not determine the size of an outage, and a plateau from 25 m/s (Beaufort 10) above which the customers affected in a district are bounded by network topology — a constraint the unconstrained fit does not reject — while restoration time keeps growing. Both are estimated with intervals, both survive district-grouped resampling, nested cross-validation and an independent temporal split, and neither is a turning point of a parabola. The critical wind speed of 10.8 m/s reported from a quadratic fit in an earlier version of this analysis is the vertex of a curve forced through a response with a floor and a plateau; its instability between samples was a symptom of mis-specification, and we recommend against its use."),
P("The district-day fragility function is the result that connects operational records to the engineering literature. It has the same lognormal form as component fragility curves [7–10, 28, 30], a median of 23–25 m/s for an outage of up to 100 customers in a district, and a floor for faults that do not depend on weather. Its median is well below those reported for the structural failure of individual poles or towers, as it should be: a district contains thousands of spans, conductors and vegetation-clearance margins, any of which can fail, so the network-level median is an extreme-value quantity of the component distribution. Convolved with a district gust hazard curve, the function gives the annual frequency of an outage of a given size per district — a calculation the incident-level regressions cannot support, and the natural next step. The near-coincidence of the weather-attributed curves across size thresholds says that the question for a storm is not whether the outage will be large but whether it will occur, which is also why the incident-conditional models, which ask how large, explain so little."),
P("Three secondary findings bear on operations. Larger incidents are restored proportionally faster once 8,661 zero-customer incidents carrying a placeholder duration of exactly 1.000 h are removed from the record — consistent with dispatch prioritisation and contrary to the independence found for US utilities [26]. Wet storms produce fewer large outages and shorter restorations than dry ones at the same gust; whether this reflects conductor loading, forecast quality or storm type cannot be resolved here. And the low mode of the restoration-time distribution, at 30–35 minutes, is automatic reclosure, which weather alone cannot separate from sustained faults; a reclosure flag would be the most useful single addition to the record."),
P("The district gust used for the fragility function is interpolated from the same day's incident locations; it is validated against held-out districts but a gridded daily maximum should replace it. The models contain no asset information, the confirmation sample covers a single winter, and the curves above 30 m/s rest on a few hundred district-days. The approach — reconstructing event-level outcomes from stage-level records, estimating rather than assuming the shape of the response, and moving from incidents to exposure units — applies to any operator that reports at stage level."),

H1("Methods"),
H3("Data and outcome construction"),
P("UKPN's outage records for 1 April 2021 – 31 March 2024, reported under Ofgem's RIIO-ED1/ED2 Annex F guidance [11, 12], comprise 116,064 restoration stages. Incidents are grouped by cause code into six categories; the weather-related and asset-related categories (network faults; 60,453 incidents) are retained and the four others (no fault found, third-party, human error, customer-side) excluded as unrelated to wind by construction. Affected customers Cᵢ is the sum over an incident's stages of the customers reported at each stage, excluding re-interruption stages; restoration duration Dᵢ is the span from earliest stage start to latest stage end. Weather at each incident's coordinates and starting hour is taken from ERA5-based hourly reanalysis via Open-Meteo [13, 14]: instantaneous gust, temperature, mean sea-level pressure and 24-h cumulative precipitation. District covariates (log population, income deprivation rate, within-district deprivation range, Moran's I of deprivation, urban–rural indicator) are from ONS [17–20]. After weather matching and covariate completeness the exposure sample has 60,437 incidents. The recovery sample excludes durations above the 99th percentile (59,834) and then incidents that interrupted no customers (51,173): 66.5% of those carry a duration of exactly 1.000 h against 0.5% of other incidents, and a restoration time is undefined when nobody was interrupted. Weather-attributed samples restrict to cause codes naming weather (9,857 and 9,254)."),
H3("Regression models"),
P("Both margins are fitted by ordinary least squares on the log outcome (log(1 + Cᵢ); log Dᵢ) with weather covariates standardised on the training sample, unstandardised district covariates, and additive year and month effects. The exposure model uses a three-segment gust response — a free slope below the onset knot k₁ (min(g, k₁)), a ramp between the knots (min(max(g − k₁, 0), k₂ − k₁)) and no term beyond k₂, so that affected customers are constant above the plateau knot — with gust × pressure, and temperature and its square; the recovery model uses gust and gust², gust × precipitation, temperature and its square, and log(1 + Cᵢ) and its square. District fixed effects are excluded because with 110 dummies the model is best in-sample and worst when whole districts are held out (cross-validated RMSE 2.10 against 1.99 for exposure). Negative-binomial, gamma and Tweedie alternatives give the same gust coefficients in sign and significance (Supplementary H)."),
H3("Specification search and knot estimation"),
P("Candidate gust forms (linear, quadratic, cubic, log, percentile step dummies, one-knot hinge, unconstrained two-hinge, and the three-segment plateau) are compared with the same covariates on AIC, BIC and out-of-sample RMSE under three cross-validation schemes: random incident split, five folds of whole districts, and leave-one-year-out. Knots are estimated by profiling the residual sum of squares over 1 m/s grids (single knot 8–30 m/s; pairs k₁ ∈ 8–20, k₂ ∈ 18–34, gap ≥ 4 m/s) [27]; two knots are tested against one by likelihood ratio (2 df), a joint 95% region is the set of pairs within the χ²₂ critical value of the optimum, and percentile intervals come from 500 bootstrap resamples of whole districts with knots re-estimated each time. A two-knot model is retained only if the second knot is significant at 1% and both bootstrap intervals are at most 6 m/s wide; the plateau constraint (zero slope beyond k₂) is tested against the unconstrained two-hinge form by likelihood ratio with one degree of freedom. Nested cross-validation re-selects the knots inside each district-grouped training fold. Knots are re-estimated on the weather-attributed samples."),
H3("Validation and inference"),
P("The primary validation holds out whole districts (five folds), with standardisation and knot selection repeated inside each training fold; leave-one-year-out is secondary; a random incident split is reported for comparison only. The final specifications are also fitted separately on a development sample (to 29 September 2023) and a confirmation sample (30 September 2023 – 31 March 2024) [23]. Standard errors are clustered by district and by date simultaneously [24, 29], with p-values from a t distribution on 110 degrees of freedom; district-only clustering understates the gust-term standard errors by a factor of 1.3–2.3. Marginal out-of-sample R² by variable group is obtained by adding blocks (district + calendar; non-gust weather; gust; affected customers) in sequence under district-grouped cross-validation."),
H3("District-day panel and fragility functions"),
P("The panel comprises the 121,656 combinations of 111 districts and 1,096 days. Daily district gust and precipitation are interpolated to each district's incident-weighted centroid from that day's incident-level observations by Gaussian-kernel inverse-distance weighting (bandwidth 40 km, minimum five neighbours); every date has at least 15 incidents in at least 13 districts, and incident gusts within a district-day have a standard deviation of about 1.8 m/s. Leaving each district's own incidents out, the interpolated gust reproduces the observed district-day mean with RMSE 2.2 m/s, correlation 0.85 and bias −0.08 m/s. Damage states are defined by the largest outage in the district on the day (any; >5; >100; >1,000 customers), for any cause and for weather-attributed cause. The fragility function P(DS ≥ k | g) = p₀ + (1 − p₀)Φ((ln g − ln θ)/β) is fitted by binomial maximum likelihood [28, 30] with p₀ on a logit scale and multiple starting values. The gust × precipitation surface is a probit in ln g, ln(1 + p), their product and log population, with monotonicity in gust checked from the sign of the partial derivative of the linear index over the observed domain."),
H3("Data availability"),
P("Analysis samples, the district-day panel and all results tables are provided with the code package. [Deposit DOI to be added.] The underlying stage-level records are available from UK Power Networks under its open-data licence."),
H3("Code availability"),
P("All analysis and figure code (Python 3.12; pandas, numpy, scipy, statsmodels, matplotlib) is provided in the package STST2603_review. [Repository URL to be added.]"),
H1("References"),...refPars,
H1("Supplementary Information (from the extended paper)"),
B("Supplementary Fig. 1: knot estimation — profiles, likelihood-ratio surface, bootstrap (extended Fig. 4)"),B("Supplementary Fig. 2: marginal out-of-sample R² by variable group, both samples (extended Fig. 7)"),B("Supplementary Fig. 3: incident-level exceedance curves and why they are not fragility functions (extended Supplementary H)"),B("Supplementary Fig. 4: final-model responses with clustered bands and out-of-fold calibration (extended Fig. 5)"),B("Supplementary Fig. 5: predicted-versus-observed grids and residual bias by gust band (extended Supplementary G)"),B("Supplementary Fig. 6: storm-by-storm predicted-versus-observed (extended Supplementary I)"),B("Supplementary Tables: specification ladder; full coefficient tables; weather-attributed coefficients; development/confirmation comparison; fragility parameters with surfaces")];

const mk=(children,out)=>{const doc=new Document({numbering,styles,sections:[{properties:props,children}]});return Packer.toBuffer(doc).then(b=>{fs.writeFileSync(out,b);console.log("written",out);});};
mk(ext,path.join(RES,"paper/Extended_paper_draft.docx")).then(()=>mk(nc,path.join(RES,"paper/NatComms_extract_draft.docx")));
